### ISSUE TITLE
A possible enhancement......

### ISSUE THREAD

**Issue by geogerar** [anaglik/ANDLineChartView#4]
Hello,
First of all I would like to thank you for your excellent tool.
Now, I propose an enchancement if it is possible of course.
Can we have two(2) lines in graph?
I mean to have two values of each point so I could have a two line graph........
If you can make it it will be a nice addition.
Thanks again...

George Gerardis

**Comment by anaglik** [comment]
Hi, 
Thanks for comment. 
Currently, I don't have much time to implement this feature but any addition from your side is welcomed.
