### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Nandulucky** [anaglik/ANDLineChartView#6]
Im working on LineChartView, But i got an issue .

ld: library not found for -lPods-ANDLineChartView
clang: error: linker command failed with exit code 1 (use -v to see invocation).

**Comment by anaglik** [comment]
Hi, 
To run the example project, just clone repo and open ANDLineChartView.xcworkspace not .xcodeproj.
