### ISSUE TITLE
X axle can't display?

### ISSUE THREAD

**Issue by liujieyuu** [anaglik/ANDLineChartView#8]
X axle can't display?

**Comment by anaglik** [comment]
No, currently it is not available.

**Comment by liuyan3176** [comment]
use VFL to narrow the height of the _internalChartView and add the label in the bottom of the _scrollView so you can get the simple X axis

**Comment by silviu-geronimo** [comment]
@liujieyuu did you manage to add x axis labels?

**Comment by liujieyuu** [comment]
@silviu-geronimo YES

**Comment by anaglik** [comment]
Would you like to add pull request for it ?
